Fix Virtual Chassis Master Update Function for Tag Input
An error occurs when we update the virtual chassis to set the master position.
The function that updates the master reads the API to get the current values
of the virtual chassis. The tag object that is received includes values
that are not expected to be sent on a PUT to the API. This commit modifies the virtual
chassis update code so that only the expected values for tags are sent, the
rest of the values are either zero-ed out or nullified.

This only seems to happen when a virtual chassis has a tag.

Error message:
```
Error: [PUT /dcim/virtual-chassis/{id}/][400] dcim_virtual-chassis_update
default  map[tags:[[Cannot resolve keyword 'display' into field.
Choices are: aggregate, asn, asnrange, cable, circuit, circuittermination,
circuittype, cluster, clustergroup, clustertype, color, configtemplate,
consoleport, consoleserverport, contact, contactassignment, contactgroup,
contactrole, created, datasource, description, device, devicebay, devicerole,
devicetype, extras_taggeditem_items, fhrpgroup, frontport, id, interface,
inventoryitem, inventoryitemrole, ipaddress, iprange, journalentry, l2vpn,
l2vpntermination, last_updated, location, manufacturer, module, modulebay,
moduletype, name, object_types, platform, powerfeed, poweroutlet, powerpanel,
powerport, prefix, provider, provideraccount, providernetwork, rack,
rackreservation, rackrole, rearport, region, rir, role, routetarget,
service, servicetemplate, site, sitegroup, slug, tenant, tenantgroup,
virtualchassis, virtualdevicecontext, virtualmachine, vlan, vlangroup,
vminterface, vrf, webhook, wirelesslan, wirelesslangroup, wirelesslink]]]
```